# PYTANIE 1 a)

\textcolor{red}{DECYZJA:} 

Przyjmujemy wszystkich chorych z cukrzycą do próby klinicznej.


\textcolor{red}{DLACZEGO?}
\begin{itemize}
\item Na wysokie ryzyko skutków ubocznych dla tych pacjentów nie wpływa rodzaj podawanego leku (SIREN lub LUCENTIS), tylko sposób jego podawania (zastrzyki w gałkę oczną). Efekty uboczne pojawią się więc zarówno w grupie eksperymentalnej, jak i kontrolnej (w kontrolnej być może częściej, z racji tego, że LUCENTIS podajemy co miesiąc, a SIREN co trzy miesiące). Nie będziemy więc błędnie wnioskować o nadmiernych efektach ubocznych SIREN-u. 
\item W fazie trzeciej głównie interesuje nas efekt działania leku, a nie jego skutki uboczne. Nie należy więc z powodu ewentualnych skutków ubocznych ograniczać wybór pacjentów.
\end{itemize}

# PYTANIE 1 b)

\textcolor{red}{DECYZJA:} 

Zostawiamy wybór lekarzom.

\textcolor{red}{DLACZEGO?}

- Główną przyczyną wykluczenia starszych ludzi z próby miałoby być większe ryzyko zgonu w czasie jej trwania (z powodu podeszłego wieku, a nie wpływu działania leku, ewentualnie z powodu skutków ubocznych). Lekarz oceni stan zdrowia pacjenta pod kątem długotrwałego udziału w próbie klinicznej.

- Wiek miał wpływ na efekty uboczne leku, a nie na efekt działania leku, nie powinniśmy więc brać go zbytnio pod uwagę w trzeciej fazie próby klinicznej.

- Przed ropoczęciem próby konsultujemy z EMA udział starszych pacjentów w badaniu.








